### ISSUE TITLE
Opcode PING should be responded with PONG

### ISSUE THREAD

**Issue by hiperbou** [Vexcited/tcp-websocket#2]
Is this correct?
https://github.com/Vexcited/tcp-websocket/blob/main/src/index.ts#L367

I think it should be sending a PONG back instead of a PING.

**Comment by Vexcited** [comment]
Hello!

You're absolutely right.
Thanks you for telling !

Let me fix this real quick.

**Comment by Vexcited** [comment]
Should be fixed in 0.2.0, please reopen this issue if you face any issue.
https://github.com/Vexcited/tcp-websocket/releases/tag/v0.2.0
